AWSTemplateFormatVersion: "2010-09-09"
Description: "Create AWS Resources"

Resources:

    MyS3Bucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
            BucketName: datalakegrp04

    MyS3Bucket1:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
            BucketName: outputgrp04
        
        
    GlueDatabase:
        Type: AWS::Glue::Database
        Properties:
            CatalogId: !Ref AWS::AccountId
            DatabaseInput:
                Name: gitdatabase 
                   

    WorkflowJob:
        Type: AWS::Glue::Workflow
        Properties:
            Description: Create workflow
            MaxConcurrentRuns: 1
            Name: jobworkflow        
    
    GlueJobImport:
        Type: AWS::Glue::Job
        DependsOn: MyS3Bucket
        Properties:
            Name: data-ingestion
            Description: Ingests data from s3 and writes it as a parquet file to the data lake
            ExecutionClass: FLEX
            GlueVersion: 4.0
            MaxRetries: 0
            NumberOfWorkers: 6
            Role: arn:aws:iam::179211392568:role/LabRole
            Timeout: 40
            WorkerType: G.1X
            Command:
                Name: glueetl
                ScriptLocation: s3://mybcktt1/Datawarehouse_Script.py

    
    GlueCrawler:
        Type: AWS::Glue::Crawler
        Properties:
            Name: CrawlingData
            DatabaseName:  gitdatabase
            Targets:
                S3Targets:
                    - Path: s3://datalakegrp04/datawarehouse/
            Role: arn:aws:iam::179211392568:role/LabRole
    
  
    WorkflowStartTrigger:
          Type: AWS::Glue::Trigger
          Properties:
              Name: StartTrigger
              Type: ON_DEMAND
              Description: Trigger for starting the workflow
              Actions:
                - JobName: !Ref GlueJobImport
              WorkflowName:  !Ref WorkflowJob

    CrawlerJobTrigger:
        Type: AWS::Glue::Trigger
        Properties:
            Name: Jobsuccesful
            Type: CONDITIONAL
            StartOnCreation: TRUE
            Description: Trigger to start the crawler
            Actions:
              - CrawlerName :  crawlingdata
            Predicate: 
              Conditions:
                - LogicalOperator: EQUALS
                  JobName: !Ref GlueJobImport
                  State: SUCCEEDED
            WorkflowName: !Ref WorkflowJob  
            
            
    MyAthenaWorkGroup:
        Type: AWS::Athena::WorkGroup
        Properties:
            Name: gitworkgrp1
            Description: workgroup for Athena
            State: ENABLED
            WorkGroupConfiguration:
                BytesScannedCutoffPerQuery: 200000000
                EnforceWorkGroupConfiguration: false
                PublishCloudWatchMetricsEnabled: true
                RequesterPaysEnabled: true
                ResultConfiguration:
                    OutputLocation: s3://outputgrp04/Query/ 

